name: Push to main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"
      - name: Format
        run: |
          cd practice/exercism
          go fmt ./...
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "format" || exit 0
          git push
